/*
 * Regenerates the esports tab's vendored assets from a live-lol-esports checkout:
 * SVG icons as Svelte components, audio and static images, and the scoped CSS.
 *
 * The ported stylesheets are rewritten so every selector is prefixed with
 * `.esports` and the app's own palette variables are bridged onto this site's
 * theme tokens. Hand-written adjustments belong in css/overrides.css instead,
 * which this script does not touch.
 *
 * `src/lib/esports/api.ts` and `types.ts` are hand-maintained ports, not outputs
 * of this script. The esports API key lives in api.ts.
 *
 * Usage: node scripts/port-esports.mjs <path-to-live-lol-esports-checkout>
 */
import { execFileSync } from 'node:child_process';
import { copyFileSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const SRC = process.argv[2];
if (!SRC) {
	console.error('usage: node scripts/port-esports.mjs <path-to-live-lol-esports-checkout>');
	process.exit(1);
}

const ROOT = new URL('../', import.meta.url).pathname;
const ICONS_DIR = join(ROOT, 'src/lib/esports/icons');
const CSS_OUT = join(ROOT, 'src/lib/esports/css/esports.css');
const STATIC_DIR = join(ROOT, 'static/esports');
const AUDIO_DIR = join(STATIC_DIR, 'audio');

const ICONS = [
	'baron',
	'dragon-chemtech',
	'dragon-cloud',
	'dragon-elder',
	'dragon-hextech',
	'dragon-infernal',
	'dragon-mountain',
	'dragon-ocean',
	'gold',
	'inhibitor',
	'kill',
	'tower',
	'team-tbd'
];

const SOURCES = [
	'components/Match/styles/playerStatusStyle.css',
	'components/Schedule/styles/scheduleStyle.css',
	'components/Sidebar/Sidebar.css'
];

/** Prefix every selector with `scope`, leaving at-rule preludes and keyframe steps alone. */
function scopeCss(input, scope) {
	// Collapse comments to single-line markers first: a comment sitting between
	// rules would otherwise be absorbed into the next rule's selector prelude.
	const comments = [];
	const css = input.replace(/\/\*[\s\S]*?\*\//g, (m) => `\u0000${comments.push(m) - 1}\u0000`);

	const out = [];
	/** Open blocks: { type: 'rule'|'step'|'media'|'keyframes', startDepth } */
	const stack = [];
	let depth = 0;
	let pending = [];

	const top = () => stack[stack.length - 1];
	// Declarations sit at the same depth as the block that opened them.
	const inDeclarations = () => {
		const frame = top();
		if (!frame) return false;
		if (frame.type !== 'rule' && frame.type !== 'step') return false;
		return depth === frame.startDepth;
	};
	const inKeyframes = () => stack.some((f) => f.type === 'keyframes');

	for (const line of css.split('\n')) {
		const trimmed = line.trim();
		if (trimmed === '') {
			out.push(line);
			continue;
		}
		const marker = trimmed.match(/^\u0000(\d+)\u0000$/);
		if (marker) {
			out.push(comments[Number(marker[1])]);
			continue;
		}
		if (trimmed === '}') {
			depth--;
			if (top() && depth < top().startDepth) stack.pop();
			out.push(line);
			continue;
		}
		const brace = line.indexOf('{');
		if (brace === -1) {
			// A declaration, or one line of a selector list that spans lines.
			if (inDeclarations()) out.push(line);
			else pending.push(line);
			continue;
		}
		const prelude = [...pending, line.slice(0, brace)]
			.join('\n')
			.replace(/\u0000(\d+)\u0000/g, (_m, id) => comments[Number(id)])
			.trim();
		pending = [];
		depth++;
		if (prelude.startsWith('@')) {
			const name = prelude.split(/\s+/)[0].slice(1);
			stack.push({ type: name === 'keyframes' ? 'keyframes' : 'media', startDepth: depth });
			out.push(`${prelude} {`);
			continue;
		}
		if (inKeyframes()) {
			stack.push({ type: 'step', startDepth: depth });
			out.push(`${prelude} {`);
			continue;
		}
		stack.push({ type: 'rule', startDepth: depth });
		const scoped = prelude
			.split(',')
			.map((s) => `${scope} ${s.trim()}`)
			.join(', ');
		out.push(`${scoped} {`);
	}
	return out.join('\n');
}

// ---------- icons: raw SVG -> Svelte component with a class passthrough ----------
mkdirSync(ICONS_DIR, { recursive: true });
for (const name of ICONS) {
	const raw = readFileSync(join(SRC, `src/assets/images/${name}.svg`), 'utf8').trim();
	// The TBD logo is hardcoded white; currentColor keeps it visible in light theme.
	const svg = raw.replace('fill="white"', 'fill="currentColor"');
	const withClass = svg.includes('class="')
		? svg.replace(/<svg([^>]*?)class="([^"]*)"/, '<svg$1class="$2 {className}"')
		: svg.replace('<svg', '<svg class="{className}"');
	writeFileSync(
		join(ICONS_DIR, `${name}.svelte`),
		`<!-- Generated by scripts/port-esports.mjs from live-lol-esports/src/assets/images/${name}.svg -->\n<script lang="ts">\n\tlet { class: className = '' } = $props();\n</script>\n\n${withClass}\n`
	);
}

// ---------- audio + static images ----------
mkdirSync(AUDIO_DIR, { recursive: true });
for (const file of readdirSync(join(SRC, 'src/assets/audios'))) {
	copyFileSync(join(SRC, `src/assets/audios/${file}`), join(AUDIO_DIR, file));
}
copyFileSync(join(SRC, 'src/assets/images/loading.svg'), join(STATIC_DIR, 'loading.svg'));

// ---------- CSS: concatenate, scope under .esports, bridge theme vars ----------
const header = `/*
 * Generated by scripts/port-esports.mjs from live-lol-esports. Do not edit:
 * put adjustments in overrides.css, which is hand-maintained.
 *
 * Selectors are scoped under .esports and the original palette is bridged onto
 * this site's theme tokens, so the tab follows the site's light/dark themes
 * instead of shipping its own.
 */
.esports {
	--background: var(--bg-primary);
	--card-color: var(--bg-secondary);
	--gray-line: var(--border);
	--text: var(--text-secondary);
	--title: var(--text-primary);
	--logo-color: var(--text-primary);
	--theme-switch-bg: var(--bg-tertiary);
	--theme-switch-notch: var(--accent);
	--blue: var(--accent);
	--purple: var(--accent);
	--red: var(--wrong);
	--green: var(--correct);
	--green-positive: var(--correct);
	/* Team sides stay blue/red: they encode data, not chrome. */
	--blue-twitter: #2aa9e0;

	color: var(--text);
	background: var(--background);
}

[data-theme='light'] .esports {
	--blue-twitter: #1477b0;
}

.esports a {
	color: inherit;
	text-decoration: none;
}

.esports button {
	cursor: pointer;
	font: inherit;
	color: inherit;
}

.esports .container {
	min-height: 0;
	max-width: none;
	padding: 0;
}

.esports #video-player[added] {
	margin-top: 10px;
	width: 100%;
	padding-top: 56.25%;
	position: relative;
}

.esports #video-player > iframe {
	position: absolute;
	top: 0;
	left: 0;
	bottom: 0;
	right: 0;
}

.esports #video-player:not([added]) > iframe {
	display: none;
}

.esports #video-player[added].chatEnabled {
	min-height: 600px;
}
`;

const body = SOURCES.map((rel) => scopeCss(readFileSync(join(SRC, `src/${rel}`), 'utf8'), '.esports')).join(
	'\n'
);
mkdirSync(join(ROOT, 'src/lib/esports/css'), { recursive: true });
writeFileSync(CSS_OUT, `${header}\n${body}\n`);

// Keep the repo format-clean; the transform above does not emit the project's formatting.
try {
	execFileSync(join(ROOT, 'node_modules/.bin/oxfmt'), [
		'--write',
		CSS_OUT,
		...ICONS.map((name) => join(ICONS_DIR, `${name}.svelte`))
	]);
} catch {
	console.warn('Could not run oxfmt — run `npm run format` to normalize the generated files.');
}

console.log(`wrote ${ICONS.length} icons to ${ICONS_DIR}`);
console.log(`copied ${readdirSync(AUDIO_DIR).length} audio files to ${AUDIO_DIR}`);
console.log(`wrote scoped css to ${CSS_OUT}`);
